
// This file has been generated by the GUI designer. Do not modify.
namespace Draw
{
	public partial class InitDraw
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Draw.InitDraw
			this.Name = "Draw.InitDraw";
			this.Title = global::Mono.Unix.Catalog.GetString ("InitDraw");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
