
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Label label1;
	private global::Gtk.Entry MyName;
	private global::Gtk.Label label2;
	private global::Gtk.Entry Mess;
	private global::Gtk.Button SayHi;
	private global::Gtk.Label MessBox;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.CanDefault = true;
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("姓名：");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.MyName = new global::Gtk.Entry ();
		this.MyName.CanFocus = true;
		this.MyName.Name = "MyName";
		this.MyName.IsEditable = true;
		this.MyName.InvisibleChar = '●';
		this.vbox1.Add (this.MyName);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.MyName]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("我想说……");
		this.vbox1.Add (this.label2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label2]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Mess = new global::Gtk.Entry ();
		this.Mess.CanFocus = true;
		this.Mess.Name = "Mess";
		this.Mess.IsEditable = true;
		this.Mess.InvisibleChar = '●';
		this.vbox1.Add (this.Mess);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.Mess]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.SayHi = new global::Gtk.Button ();
		this.SayHi.CanFocus = true;
		this.SayHi.Name = "SayHi";
		this.SayHi.UseUnderline = true;
		this.SayHi.Label = global::Mono.Unix.Catalog.GetString ("哈哈，你打我啊~");
		this.vbox1.Add (this.SayHi);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.SayHi]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 4;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.MessBox = new global::Gtk.Label ();
		this.MessBox.Name = "MessBox";
		this.vbox1.Add (this.MessBox);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.MessBox]));
		w6.PackType = ((global::Gtk.PackType)(1));
		w6.Position = 5;
		w6.Expand = false;
		w6.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.Mess.EditingDone += new global::System.EventHandler (this.OnButton3Clicked);
		this.SayHi.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
	}
}
